### ISSUE TITLE
Guide needed..

### ISSUE THREAD

**Issue by XL2014** [TheTorProject/gettorbrowser#1]
Tor browser won't work directly in China but it will work by using meek-azure and meek-amazon..
I wrote a guide in Chinese on how to make Tor Browser work in China..
Could you put a link to guide to make people in China that don't understand English or don't know how to config meek to know how to make Tor Browser works?
Thank you!

Guide Below:
## 下载 Tor Browser 及 签名文件

在 https://github.com/TheTorProject/gettorbrowser 页面中，选择您的操作系统（Windows/OS X/Linux）

点击Download Tor Browser (Chinese) 下载Tor Browser中文版程序..

之后在后面的signature file上 右键——另存为 保存到本机..
## 通过数字签名验证 Tor Browser

在下载好的Tor图标上进行 右键,点击属性

<img src="https://cloud.githubusercontent.com/assets/8599973/14095763/038a870e-f596-11e5-809b-ccaf959cafb6.png">

如果出现了“数字签名”选项卡，则代表文件正常。如果没有”数字签名“选项卡，则需要重新下载。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095768/0fe1e4f2-f596-11e5-9da2-a7529bee840e.png">
## 通过asc文件验证 TorBrowser 签名文件

点击 https://files.gpg4win.org/gpg4win-2.3.0.exe 下载GPG4Win

下载完成后,按照上面的方法验证是否有“数字签名”选项卡，如果有，则继续看下一步，如果没有，则重新下载。

双击安装程序，一路下一步即可完成安装。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095773/2aa71988-f596-11e5-9c4a-1c25c6e8846c.png">

使用组合键 Win+R 或 开始——运行 跳出运行，输入 cmd 打开命令提示符。

在跳出的黑框中输入

gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290 

回车

之后输入

gpg  --fingerprint 0x4E2C6E8793298290

回车

你应该会看到

> pub   4096R/93298290 2014-12-15 [expires: 2020-08-24]
> 
> ```
>   Key fingerprint = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
> ```
> 
> uid       [ unknown] Tor Browser Developers (signing key) torbrowser@torproject.org
> 
> sub   4096R/F65C2036 2014-12-15 [expires: 2017-08-25]
> 
> sub   4096R/D40814E0 2014-12-15 [expires: 2017-08-25]

<img src="https://cloud.githubusercontent.com/assets/8599973/14095778/39a396e6-f596-11e5-8de6-0fbc6d92a211.png">

之后输入 gpg --verify 先不要按回车， 将asc文件拖拽到黑框中，之后输入一个空格，然后将exe文件拖拽到黑框中。看起来像这样。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095782/4a47a7e4-f596-11e5-9f75-fa55f29787df.png">

之后按回车，稍等几秒后会有“Good Signature” 的提示。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095787/5aa454a2-f596-11e5-8015-5d4d440d47ad.png">

如果没出现Good Signature的提示，请重新下载。
## 安装 Tor Browser

双击运行安装程序,提示选择语言,保持默认的“Chinese (Simplified)”，点击OK

<img src="https://cloud.githubusercontent.com/assets/8599973/14095794/68e432bc-f596-11e5-884f-e6c50748f3cc.png">

点击OK之后，出现安装路径，保持默认的话是在桌面上建立一个文件夹。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095798/6cd15c4c-f596-11e5-8002-ac655c334495.png">

下一步之后，等待安装进度，然后等待安装完成。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095799/6fccd430-f596-11e5-95c4-db05e2ef796b.png">

至此，安装已经完成
## 配置 Tor Browser

双击桌面上的Tor Browser (绿色的浏览器图标),跳出配置界面

<img src="https://cloud.githubusercontent.com/assets/8599973/14095812/83ec9b9e-f596-11e5-9d88-1f0a919d1302.png">

选择"配置"按钮，点击下一步。

之后会问你：“你的网络是否遭到审查”，选择是

<img src="https://cloud.githubusercontent.com/assets/8599973/14095815/87c5f378-f596-11e5-832d-e67f63255a27.png">

下一步之后，会让你选择网桥，在这里我们选择 meek-azure 或 meek-amazon

<img src="https://cloud.githubusercontent.com/assets/8599973/14095818/8ade1a72-f596-11e5-9f5a-fba71e33fe01.png">

选择完毕后，点击下一步。

下一步之后，会提示你是否使用代理，一般情况下选择否。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095819/8e37817c-f596-11e5-8783-0837f0a97e06.png">

点击“连接”按钮进行翻墙

<img src="https://cloud.githubusercontent.com/assets/8599973/14095821/912998f2-f596-11e5-9190-a2183c52c828.png">

第一次使用稍等大概1-2分钟，之后就可以翻墙了：），以后不用等这么久。

<img src="https://cloud.githubusercontent.com/assets/8599973/14095824/940d62f6-f596-11e5-932c-5601be832519.png">

**Comment by ilv** [comment]
Hello @XL2014, thanks for the suggestion! (and sorry for the delay in responding).

Right now gettor does not send guides, but we might do that in the future. If this guide is intended to meek users, you should take a look at this [wiki page](https://trac.torproject.org/projects/tor/wiki/doc/meek) (there are howtos in other languages, although none of them seem to cover the signature verification process).

**Comment by percyalpha** [comment]
This guide is very useful to Chinese user. Maybe Tor can include this as a link somewhere during the launch process

**Comment by 1009351456** [comment]
this guide is very useful! thank u!

**Comment by ilv** [comment]
Closing old tickets. FYI this guide is linked in the [meek wiki page](https://trac.torproject.org/projects/tor/wiki/doc/meek).
