### ISSUE TITLE
where are the releases?

### ISSUE THREAD

**Issue by WaffleMongeringShit** [TheTorProject/gettorbrowser#1]
where are the releases?

**Comment by hiromipaw** [comment]
Hey,
We are having some issues here on github, but all our files are available here too:


- Gitlab.com: https://gitlab.com/thetorproject/gettorbrowser/raw/torbrowser-releases/
- Internet Archive: https://archive.org/details/@gettor
- Google Drive folder: https://drive.google.com/open?id=13CADQTsCwrGsIID09YQbNz2DfRMUoxUU

**Comment by eloquence** [comment]
That GitLab link produces a 404, but https://gitlab.com/thetorproject/gettorbrowser/tree/torbrowser-releases appears to work.

**Comment by massood** [comment]
FYI, access to GitLab is blocked in at least six countries, thanks to [Google Cloud Platform discriminations](https://about.gitlab.com/blog/2018/07/19/gcp-move-update/). Ironically, those are the countries with the most censored and surveilled Internet access. Viva Internet Archive.

**Comment by oliv3r** [comment]
@hiromipaw Not wanting to re-open this old issue, or re-create a new one; but gitlab still produces a 404. Going to the user root gitlab states that the account is set to private, thus cannot be accessed :(
