### ISSUE TITLE
dmg wont extract 

### ISSUE THREAD

**Issue by anupamkumar** [TheTorProject/gettorbrowser#10]
<img width="369" alt="screen shot 2017-02-08 at 11 42 16 am" src="https://cloud.githubusercontent.com/assets/3490199/22754342/118d12b6-edf4-11e6-814c-6da0471f75d7.png">

Got the DMG file from https://www.torproject.org/download/download-easy.html.en

MAC OS X details

<img width="582" alt="screen shot 2017-02-08 at 11 46 27 am" src="https://cloud.githubusercontent.com/assets/3490199/22754408/4617b234-edf4-11e6-95bb-a4de7a5f5317.png">

**Comment by z3t0** [comment]
Do you have the same issue with other dmgs?

**Comment by ilv** [comment]
Hi. This is just a mirror of Tor Browser packages. For Tor Browser issues please use Tor Project's trac (https://trac.torproject.org/projects/tor/newticket). In Component, you should select Applications, then Tor Browser.
