### ISSUE TITLE
Hardened  tor browser is not working for tiny core linux

### ISSUE THREAD

**Issue by shree007** [TheTorProject/gettorbrowser#11]
Hello Guys

I am trying to run tor browser at tinycore linux which is installed at oracle VirtualBox . For that i have downloaded hardened tor browser and use this command in terminal "./start-tor-browser.desktop" , it is showing that it is launching(refer image) but I have not got any tor browser.

![launch](https://cloud.githubusercontent.com/assets/13500205/23693887/e11df860-03fc-11e7-9c4a-0c34f77b2c50.PNG)

**Comment by ilv** [comment]
Hi. This is just a mirror of Tor Browser packages. For Tor Browser issues please use Tor Project's trac (https://trac.torproject.org/projects/tor/newticket). You should select Applications, then Tor Browser.
