### ISSUE TITLE
Disable issues

### ISSUE THREAD

**Issue by hellais** [TheTorProject/gettorbrowser#14]
I noticed that you are closing issues and requesting that people file them on trac instead, which I think is fine.

I would suggest in that case that you disable issues from github (and possibly also wiki) to avoid confusing users and maybe add a note about it inside of the readme pointing to trac.

You can do so by going to the settings tab of the repository (I can also do it if you think it's a good idea):

![screen shot 2017-06-26 at 05 59 06 0200](https://user-images.githubusercontent.com/424620/27524386-c70f4da0-5a34-11e7-8afc-81cab2187cc7.png)

**Comment by ilv** [comment]
Thanks, this is a good idea. Will do it.
