### ISSUE TITLE
Is it possible for you to sign the compiled browser bundle binary?

### ISSUE THREAD

**Issue by kevinSuttle** [TheTorProject/gettorbrowser#2]
Not sure what the implications of something like this are. 
https://support.apple.com/en-us/HT202491

**Comment by ilv** [comment]
Hello,

I'm not part of the team who develops and signs the tor browser bundle, but I've asked around and they do use a developer id from apple. In addition, all the bundles are signed using pgp signatures (the .asc files in this repository). I hope this answers your concern.

Thanks.

**Comment by ilv** [comment]
**Correction**: the OS X signing process for Tor Browser will arrive soon, but it does not happen currently. More info [here](https://trac.torproject.org/projects/tor/ticket/6540).
