### ISSUE TITLE
source tarball

### ISSUE THREAD

**Issue by rofl0r** [TheTorProject/gettorbrowser#6]
i can't find the link to download the torbrowser source code.
i know that i can get the source from git, but i suspect a source tarball (preferable .xz compressed due to firefox' huge size) would be helpful for various source-based distros.

**Comment by rofl0r** [comment]
not even worth an answer ?

**Comment by ilv** [comment]
Sorry, I didn't thought a reply would be useful after almost ten months. There is no way to download other than cloning the git repository.

**Comment by ilv** [comment]
Also, this is just a mirror. For bugs/tickets please use trac (https://trac.torproject.org), and select Applications/Tor Browser under the Component field.
